SELECT
    (COUNT(DISTINCT ?publication) AS ?total)
    (COUNT(DISTINCT ?publicationAA) AS ?articles)
    (COUNT(DISTINCT ?publicationAAPR) AS ?peerreviewed)
    (COUNT(DISTINCT ?publicationBook) AS ?books)
    (COUNT(DISTINCT ?publicationReport) AS ?reports)
    (COUNT(DISTINCT ?publicationProposal) AS ?proposals)
    (COUNT(DISTINCT ?publicationChapter) AS ?chapters)
    (COUNT(DISTINCT ?publicationConfPaper) AS ?confpapers)
    (COUNT(DISTINCT ?publicationSlideshow) AS ?slideshows)
    (COUNT(DISTINCT ?publicationDataset) AS ?datasets)
    (COUNT(DISTINCT ?publicationConfPoster) AS ?confposters)
    (COUNT(DISTINCT ?publicationManual) AS ?manuals)
    (COUNT(DISTINCT ?publicationEA) AS ?editorials)
    (COUNT(DISTINCT ?publicationAbstract) AS ?abstracts)
    (COUNT(DISTINCT ?publicationThesis) AS ?theses)
    (COUNT(DISTINCT ?publicationVideo) AS ?videos)
WHERE
{
    {
        ?publication a ?type .
        ?publication <http://lod.tib.eu/onto/kdsf/hatZugriffsrechte> <http://purl.org/coar/access_right/c_abf2> .
    }
    UNION
    {
        ?publicationAA a <http://purl.org/ontology/bibo/AcademicArticle> .
        ?publicationAA <http://lod.tib.eu/onto/kdsf/hatZugriffsrechte> <http://purl.org/coar/access_right/c_abf2> .
    }
    UNION
    {
        ?publicationAAPR a <http://purl.org/ontology/bibo/AcademicArticle> .
        ?publicationAAPR <http://purl.org/ontology/bibo/status> <http://purl.org/ontology/bibo/peerReviewed> .
        ?publicationAAPR <http://lod.tib.eu/onto/kdsf/hatZugriffsrechte> <http://purl.org/coar/access_right/c_abf2> .
    }
    UNION
    {
        ?publicationBook a <http://purl.org/ontology/bibo/Book> .
        ?publicationBook <http://lod.tib.eu/onto/kdsf/hatZugriffsrechte> <http://purl.org/coar/access_right/c_abf2> .
        MINUS { ?publicationBook a <http://purl.org/ontology/bibo/Proceedings> . }
    }
    UNION
    {
        ?publicationReport a <http://purl.org/ontology/bibo/Report> .
        ?publicationReport <http://lod.tib.eu/onto/kdsf/hatZugriffsrechte> <http://purl.org/coar/access_right/c_abf2> .
    }
    UNION
    {
        ?publicationReport a <http://vivoweb.org/ontology/core#WorkingPaper> .
        ?publicationReport <http://lod.tib.eu/onto/kdsf/hatZugriffsrechte> <http://purl.org/coar/access_right/c_abf2> .
    }
   UNION
    {
        ?publicationReport a <http://kerndatensatz-forschung.de/owl/Basis#ArbeitspapierForschungsbericht> .
        ?publicationReport <http://lod.tib.eu/onto/kdsf/hatZugriffsrechte> <http://purl.org/coar/access_right/c_abf2> .
    }
   UNION
    {
        ?publicationProposal a <http://vivoweb.org/ontology/core#ResearchProposal> .
         ?publicationProposal <http://lod.tib.eu/onto/kdsf/hatZugriffsrechte> <http://purl.org/coar/access_right/c_abf2> .
    }
    UNION
    {
        ?publicationChapter a <http://purl.org/ontology/bibo/Chapter> .
        ?publicationChapter <http://lod.tib.eu/onto/kdsf/hatZugriffsrechte> <http://purl.org/coar/access_right/c_abf2> .
    }
    UNION
    {
        ?publicationConfPaper a <http://vivoweb.org/ontology/core#ConferencePaper> .
        ?publicationConfPaper <http://lod.tib.eu/onto/kdsf/hatZugriffsrechte> <http://purl.org/coar/access_right/c_abf2> .
    }
    UNION
    {
        ?publicationSlideshow a <http://purl.org/ontology/bibo/Slideshow> .
        ?publicationSlideshow <http://lod.tib.eu/onto/kdsf/hatZugriffsrechte> <http://purl.org/coar/access_right/c_abf2> .
    }
    UNION
    {
        ?publicationDataset a <http://vivoweb.org/ontology/core#Dataset> .
        ?publicationDataset <http://lod.tib.eu/onto/kdsf/hatZugriffsrechte> <http://purl.org/coar/access_right/c_abf2> .
    }
    UNION
    {
        ?publicationConfPoster a <http://vivoweb.org/ontology/core#ConferencePoster> .
        ?publicationConfPoster <http://lod.tib.eu/onto/kdsf/hatZugriffsrechte> <http://purl.org/coar/access_right/c_abf2> .
    }
    UNION
    {
        ?publicationManual a <http://purl.org/ontology/bibo/Manual> .
        ?publicationManual <http://lod.tib.eu/onto/kdsf/hatZugriffsrechte> <http://purl.org/coar/access_right/c_abf2> .
    }
    UNION
    {
        ?publicationEA a <http://vivoweb.org/ontology/core#EditorialArticle> .
        ?publicationEA <http://lod.tib.eu/onto/kdsf/hatZugriffsrechte> <http://purl.org/coar/access_right/c_abf2> .
    }
    UNION
    {
        ?publicationAbstract a <http://vivoweb.org/ontology/core#Abstract> .
        ?publicationAbstract <http://lod.tib.eu/onto/kdsf/hatZugriffsrechte> <http://purl.org/coar/access_right/c_abf2> .
    }
    UNION
    {
        ?publicationThesis a <http://purl.org/ontology/bibo/Thesis> .
        ?publicationThesis <http://lod.tib.eu/onto/kdsf/hatZugriffsrechte> <http://purl.org/coar/access_right/c_abf2> .
    }
    UNION
    {
        ?publicationVideo a <http://vivoweb.org/ontology/core#Video> .
        ?publicationVideo <http://lod.tib.eu/onto/kdsf/hatZugriffsrechte> <http://purl.org/coar/access_right/c_abf2> .
    }
}