Select
(sum ( ?budget_eu) as ?eu)

Where 
{
    ?project_eu a <http://vivoweb.org/ontology/core#Grant> .
 	?project_eu <http://vivoweb.org/ontology/core#assignedBy> <http://your.vivo/data/eu_uri_here> . # An dieser Stelle muss die URI der EU-Instanz aus Ihrem VIVO eingesetzt werden.
  	?project_eu <https://local.ontology/local-vivo#budgetLocal> ?budget_eu.
}